"""
ISRDS PMO Agent — Google ADK Runtime
Generated by the isrds-agent-builder skill (Phase 8).

This agent reads live Jira data via the Atlassian MCP server, tracks project status,
blockers, and RACI ownership. It drafts follow-up pings for stalled/orphaned tickets
and creates human gates (Review, Escalate, Flag) per the governance rules.

Authority: DECIDE_AND_REPORT — reads, reasons, reports; never auto-posts.
Build posture: ABSORB into existing codebase (extends BaseRoleAgent).

Local testing:  cd examples/pmo-agent/adk && adk web .
Deploy:         adk deploy --project $GOOGLE_CLOUD_PROJECT --location us-central1
"""
import os
from pathlib import Path

from google.adk.agents import LlmAgent
from google.adk.tools import FunctionTool
from google.adk.tools.mcp_tool.mcp_toolset import MCPToolset
from google.adk.tools.mcp_tool.mcp_session_manager import StreamableHTTPConnectionParams

from governance import governance_check, trust_ledger_log

# ── Load prompt from the portable artifact ──
AGENT_DIR = Path(__file__).parent.parent  # points to examples/pmo-agent/
PROMPT = (AGENT_DIR / "prompt.md").read_text()

# ── Runtime engine resolution (Layer 1) ──
# NEVER hardcoded. Resolved from environment / Config Registry.
MODEL = os.environ.get("AGENT_MODEL", "gemini-2.5-flash")

# ── MCP Tool Connections (Layer 3) ──
# Mapped from tool-registry.yaml:
#   - id: workorder_db  → integration: mcp, server: postgres
#   - id: jira          → integration: mcp, server: atlassian

# Jira MCP (Atlassian Rovo managed endpoint)
JIRA_MCP_URL = os.environ.get(
    "JIRA_MCP_URL",
    "https://mcp.atlassian.com/v1/mcp/authv2"
)
JIRA_MCP_TOKEN = os.environ.get("JIRA_MCP_TOKEN", "")

jira_tools = MCPToolset(
    connection_params=StreamableHTTPConnectionParams(
        url=JIRA_MCP_URL,
        headers={"Authorization": f"Bearer {JIRA_MCP_TOKEN}"} if JIRA_MCP_TOKEN else {},
    ),
)

# PostgreSQL MCP (work order database)
POSTGRES_MCP_URL = os.environ.get("POSTGRES_MCP_URL", "")
postgres_tools = None
if POSTGRES_MCP_URL:
    postgres_tools = MCPToolset(
        connection_params=StreamableHTTPConnectionParams(
            url=POSTGRES_MCP_URL,
        ),
    )

# ── Custom Tools (Layer 3 — no MCP server exists for these) ──

@FunctionTool
def governance_gate(gate_type: str, description: str, ticket_key: str = "") -> dict:
    """Create a human gate request. Gate types: Review, Escalate, Flag.
    The agent PAUSES here and waits for human action (Layer 6).
    Use Review for drafted pings before distribution.
    Use Escalate for tickets stalled >72h (routes to Founder).
    Use Flag for missing owners or build-gaps on critical path (routes to COO)."""
    trust_ledger_log("gate", f"Requesting {gate_type}: {description} [{ticket_key}]")
    return {
        "gate_type": gate_type,
        "description": description,
        "ticket_key": ticket_key,
        "status": "pending",
        "message": f"⏸️ {gate_type} gate created. Agent paused — awaiting human decision.",
    }


@FunctionTool
def log_decision(decision: str, rationale: str) -> dict:
    """Log a decision to the Trust Ledger (FR-7 invariant).
    EVERY reasoning step that leads to an action must call this.
    Example: log_decision('milestone_at_risk', 'ISRD-101 forecast past committed date')"""
    trust_ledger_log("decision", f"{decision}: {rationale}")
    return {"logged": True, "decision": decision}


@FunctionTool
def draft_followup_ping(
    ticket_key: str,
    assignee: str,
    stalled_hours: int,
    is_critical: bool,
    message: str
) -> dict:
    """Draft a follow-up ping for a stalled or orphaned ticket.
    This does NOT send the message — it creates a draft that goes through
    the Review gate before distribution. The COO must approve."""
    urgency = "high" if stalled_hours > 72 else "medium" if stalled_hours > 48 else "low"
    trust_ledger_log("tool-call", f"Drafted {urgency}-urgency ping for {ticket_key} → {assignee}")
    return {
        "ticket_key": ticket_key,
        "assignee": assignee,
        "message": message,
        "urgency": urgency,
        "stalled_hours": stalled_hours,
        "is_critical": is_critical,
        "status": "drafted — awaiting Review gate",
    }


# ── Compose the agent ──
tools = [
    jira_tools,
    governance_gate,
    log_decision,
    draft_followup_ping,
]
if postgres_tools:
    tools.insert(0, postgres_tools)

root_agent = LlmAgent(
    name="pmo-agent",
    model=MODEL,
    instruction=PROMPT,
    tools=tools,
    output_key="response",
)
