-- =============================================================================
-- ISRDS Survey Agent — Schema Migration
-- Run against: isrds_agentic database on AlloyDB
-- Depends on: 001_foundation.sql
-- =============================================================================

-- =============================================================================
-- Survey Templates
-- Question tree stored as JSONB. Versioned per tenant.
-- =============================================================================
CREATE TABLE IF NOT EXISTS survey_templates (
  id           UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id    TEXT        NOT NULL,
  survey_type  TEXT        NOT NULL,  -- POST_APPOINTMENT | LEAD_QUALIFICATION | WELLNESS_CHECK
  version      INTEGER     NOT NULL DEFAULT 1,
  title        TEXT        NOT NULL,
  description  TEXT,
  -- question_tree: array of { id, text, type, follow_ups: { condition, next_question_id } }
  question_tree JSONB      NOT NULL DEFAULT '[]',
  is_active    BOOLEAN     NOT NULL DEFAULT TRUE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (tenant_id, survey_type, version)
);
ALTER TABLE survey_templates ENABLE ROW LEVEL SECURITY;
CREATE POLICY survey_templates_tenant ON survey_templates
  USING (tenant_id = current_setting('app.tenant_id', true));

-- =============================================================================
-- Survey Sessions
-- One row per conversation initiated by the agent.
-- =============================================================================
CREATE TABLE IF NOT EXISTS survey_sessions (
  id               UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id        TEXT        NOT NULL,
  template_id      UUID        REFERENCES survey_templates(id),
  survey_type      TEXT        NOT NULL,
  -- subject is the customer/lead being surveyed
  subject_type     TEXT        NOT NULL CHECK (subject_type IN ('CONTACT','LEAD','WORKORDER')),
  subject_id       TEXT        NOT NULL,
  subject_name     TEXT,
  -- delivery channel
  channel          TEXT        NOT NULL CHECK (channel IN ('SMS','IN_APP','EMAIL')),
  channel_ref      TEXT,        -- phone number or email address
  -- agentic fields
  adk_session_id   TEXT,        -- Vertex AI Agent Engine session ID
  agent_version    TEXT,
  status           TEXT        NOT NULL DEFAULT 'INITIATED'
                               CHECK (status IN ('INITIATED','IN_PROGRESS','COMPLETED','ABANDONED')),
  -- outcome
  sentiment_score  NUMERIC(4,3),  -- -1.0 to 1.0
  summary          TEXT,
  structured_data  JSONB       NOT NULL DEFAULT '{}',  -- normalised by DataAssimilation
  -- timing
  initiated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at     TIMESTAMPTZ,
  -- trust ledger ref
  trust_ledger_id  UUID        REFERENCES trust_ledger(id)
);
CREATE INDEX IF NOT EXISTS idx_survey_sessions_subject
  ON survey_sessions (tenant_id, subject_type, subject_id);
CREATE INDEX IF NOT EXISTS idx_survey_sessions_status
  ON survey_sessions (tenant_id, status, initiated_at DESC);
ALTER TABLE survey_sessions ENABLE ROW LEVEL SECURITY;
CREATE POLICY survey_sessions_tenant ON survey_sessions
  USING (tenant_id = current_setting('app.tenant_id', true));

-- =============================================================================
-- Survey Responses
-- One row per turn (question + answer pair).
-- =============================================================================
CREATE TABLE IF NOT EXISTS survey_responses (
  id              UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
  session_id      UUID        NOT NULL REFERENCES survey_sessions(id) ON DELETE CASCADE,
  tenant_id       TEXT        NOT NULL,
  turn_number     INTEGER     NOT NULL,
  question_id     TEXT,
  question_text   TEXT        NOT NULL,
  answer_text     TEXT,
  answer_type     TEXT        CHECK (answer_type IN ('FREE_TEXT','CHOICE','NUMERIC','SKIP')),
  sentiment       TEXT        CHECK (sentiment IN ('POSITIVE','NEUTRAL','NEGATIVE','DISTRESS')),
  -- embedding for pgvector memory retrieval
  embedding       vector(768),
  -- flag set by agent if distress detected
  distress_flag   BOOLEAN     NOT NULL DEFAULT FALSE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_survey_responses_session
  ON survey_responses (session_id, turn_number);
CREATE INDEX IF NOT EXISTS idx_survey_responses_embedding
  ON survey_responses USING hnsw (embedding vector_cosine_ops)
  WHERE embedding IS NOT NULL;
ALTER TABLE survey_responses ENABLE ROW LEVEL SECURITY;
CREATE POLICY survey_responses_tenant ON survey_responses
  USING (tenant_id = current_setting('app.tenant_id', true));

-- =============================================================================
-- Daily Briefings
-- Generated by Synthesizer agent nightly.
-- =============================================================================
CREATE TABLE IF NOT EXISTS daily_briefings (
  id               UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id        TEXT        NOT NULL,
  swarm_id         TEXT,
  briefing_date    DATE        NOT NULL,
  gcs_uri          TEXT,
  summary_text     TEXT,
  generated_by_role TEXT       NOT NULL DEFAULT 'Synthesizer/Reporter',
  sessions_included INTEGER    NOT NULL DEFAULT 0,
  avg_sentiment    NUMERIC(4,3),
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (tenant_id, briefing_date)
);
ALTER TABLE daily_briefings ENABLE ROW LEVEL SECURITY;
CREATE POLICY daily_briefings_tenant ON daily_briefings
  USING (tenant_id = current_setting('app.tenant_id', true));
