"""
ISRDS Agent — REPLACE-agent-id
Generated by the isrds-agent-builder skill (Phase 8 code generation).

This is a Google ADK agent. It reads its instructions from prompt.md and connects
to external tools via MCP servers. Governance rules (Layer 5) and human gates
(Layer 6) are enforced by the governance middleware.

Local testing:  adk web .
Deploy:         adk deploy --project $GOOGLE_CLOUD_PROJECT --location $GOOGLE_CLOUD_LOCATION
"""
import os
from pathlib import Path

from google.adk.agents import LlmAgent
from google.adk.tools.mcp_tool.mcp_toolset import MCPToolset
from google.adk.tools.mcp_tool.mcp_session_manager import StreamableHTTPConnectionParams

from governance import governance_check, trust_ledger_log

# ── Load prompt from the portable artifact ──
AGENT_DIR = Path(__file__).parent.parent  # points to agents/<agent_id>/
PROMPT = (AGENT_DIR / "prompt.md").read_text()

# ── Runtime engine resolution (Layer 1) ──
# The model is NEVER hardcoded. It is resolved from environment at runtime.
# In production, config_registry.resolve(tenant_id, agent_id) returns this.
MODEL = os.environ.get("AGENT_MODEL", "gemini-2.5-flash")

# ── MCP tool connections (Layer 3) ──
# Each tool in tool-registry.yaml that uses integration: mcp gets a connection here.
# REPLACE: Add one MCPToolset per MCP server your agent needs.

# Example: Atlassian Jira MCP (via Rovo managed endpoint or custom Cloud Run)
JIRA_MCP_URL = os.environ.get(
    "JIRA_MCP_URL",
    "https://mcp.atlassian.com/v1/mcp/authv2"  # Atlassian Rovo managed MCP
)
JIRA_MCP_TOKEN = os.environ.get("JIRA_MCP_TOKEN", "")

jira_tools = MCPToolset(
    connection_params=StreamableHTTPConnectionParams(
        url=JIRA_MCP_URL,
        headers={"Authorization": f"Bearer {JIRA_MCP_TOKEN}"} if JIRA_MCP_TOKEN else {},
    ),
    # Optional: filter to only the tools you need
    # tool_filter=lambda tool, ctx: tool.name in ["search_issues", "get_issue"]
)

# REPLACE: Add more MCPToolset connections for postgres, slack, etc. as needed.
# postgres_tools = MCPToolset(
#     connection_params=StreamableHTTPConnectionParams(
#         url=os.environ.get("POSTGRES_MCP_URL", "http://localhost:5433/mcp"),
#     ),
# )

# ── Custom tools (Layer 3 — only when no MCP server exists) ──
# REPLACE: Define custom ADK tools here for actions without an MCP server.

from google.adk.tools import FunctionTool

@FunctionTool
def governance_gate(gate_type: str, description: str, ticket_key: str = "") -> dict:
    """Create a human gate request. Gate types: Review, Escalate, Flag, Approve.
    This is ISRDS Layer 6 — the agent pauses and waits for human action."""
    trust_ledger_log("gate", f"Requesting {gate_type} gate: {description}")
    return {
        "gate_type": gate_type,
        "description": description,
        "ticket_key": ticket_key,
        "status": "pending",
        "message": f"⏸️ {gate_type} gate created. Agent paused — awaiting human decision.",
    }

@FunctionTool
def log_decision(decision: str, rationale: str) -> dict:
    """Log a decision to the Trust Ledger (FR-7 invariant). Every reasoning step
    that leads to an action must be recorded."""
    trust_ledger_log("decision", f"{decision}: {rationale}")
    return {"logged": True, "decision": decision}

# ── Compose the agent ──
root_agent = LlmAgent(
    name="REPLACE-agent-id",
    model=MODEL,
    instruction=PROMPT,
    tools=[
        jira_tools,
        governance_gate,
        log_decision,
        # REPLACE: add more tool connections here
    ],
    # ADK configuration
    output_key="response",
)
